import { useState } from 'react';
import Head from "next/head";
import styles from "@/styles/Dashboard.module.css";
import Sidebar from "./components/Sidebar";

export default function Dashboard() {
  const [showModal, setShowModal] = useState(false);

  const toggleModal = () => {
    setShowModal(!showModal);
  };

  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        <nav>
          <Sidebar />
        </nav>
        <main className={styles.main}>
          <div className={styles.topbar}>
            <p>test</p>
          </div>


          <div className={styles.contentWrapper}>
            <div className={styles.card}>
              <div className={styles.cardTitle}>
                <h2>Create Organizations:</h2>
              </div>
              <div className={styles.cardBody}>
                <p>
                  We see that you don't have any organizations. Create one to access and create a database.
                </p>
                <br />
                <button className={styles.bubbleButton} onClick={toggleModal}>
                  Create Organization
                </button>
              </div>
            </div>
          </div>
        </main>
      </div>

      {showModal && (
        <div className={styles.modal}>
          <div className={styles.modalContent}>
            <div className={styles.modalHeader}>
              <h2>Create a new organization:</h2>
              <button className={styles.close} onClick={showModal}>
                &times;
              </button>
            </div>
            <br />
            <div className={styles.modalBody}>
              <form className={styles.form}>
                <label className={styles.label} htmlFor="orgname">Name:</label>
                <input
                  className={styles.input}
                  type="text"
                  id='orgname'
                  placeholder='Organization name'
                  minLength="3"
                  maxLength="20"
                />
                <br></br>
                <label className={styles.label} htmlFor="typeorg">Type of organization:</label>
                <select
                  className={styles.input}
                  type="text"
                  id='vpsos'
                >
                  <option value="ubuntu-20.04">Personal</option>
                  <option value="ubuntu-18.04">Educational</option>
                  <option value="debian-10">Startup</option>
                  <option value="debian-9">Agency</option>
                  <option value="centos-8">Company</option>
                  <option value="centos-7">N/A</option>
                </select>
              </form>
              <div className={styles.modalFooterLine}></div>
              <div className={styles.modalFooter}>
                <button className={styles.bubbleButton} onClick={toggleModal}>
                  Cancel
                </button>
                  <button className={styles.bubbleButton} onClick={toggleModal}>
                    Create Organization
                  </button>
              </div>

            </div>
          </div>
        </div>
      )}
    </>
  );
}
