import { useRouter } from 'next/router';
import Head from "next/head";
import Sidebar from "../../components/Sidebar";
import styles from '@/styles/Dashboard.module.css';
import axios from 'axios';


const Manage = () => {
  const router = useRouter();
  const { token } = router.query;

  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        <nav>
          <Sidebar />
        </nav>
        <main className={styles.main}>
          <div className={styles.topbar}>
            <p>test</p>
          </div>


          <div className={styles.contentWrapper}>


            <div className={styles.card}>
              <div className={styles.cardTitle}>
                <h2>Organization Management:</h2>
              </div>
              <div className={styles.cardBody}>
                <p>Token: {token}</p>
              </div>
            </div>

          </div>
        </main>
      </div>
    </>
  );
};

export default Manage;
